spring.application.name=ims
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/rit_ims?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=nikitasree27

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

app.jwt.secret=RITChennaiIMSSecretKey2024SuperSecureJWTKeyForAuthentication
app.jwt.expiration=86400000
