CREATE DATABASE IF NOT EXISTS rit_ims;
USE rit_ims;

-- The schema will be auto-generated by Spring Boot's hibernate.ddl-auto=update.
-- Data seeding is fully managed by com.rit.ims.DataSeeder running on boot.
