CREATE DATABASE IF NOT EXISTS rit_ims;
USE rit_ims;

-- The schema will be auto-generated by Spring Boot's hibernate.ddl-auto=update.
-- But we can safely try to insert after the tables are created. 
-- For a full seed script, we will insert ignoring errors or just provide standard INSERTs 
-- assuming tables exist. But since ddl-auto=update might run after, it's customary to start 
-- the app once, let tables create, and then run the seed data, or rely on Hibernate's data.sql
-- For this Phase, provided script is manual. Ensure the app is run first to generate the tables.

-- Insert Admin
INSERT INTO users (username, password, email, full_name, role, department, phone_number, active, created_at)
VALUES ('admin', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LPVyaKT0ogy', 'admin@rit.ac.in', 'Admin User', 'ADMIN', 'Administration', '9000000000', true, NOW());

-- Insert Faculty (3 users)
INSERT INTO users (username, password, email, full_name, role, department, phone_number, active, created_at)
VALUES 
('faculty1', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LPVyaKT0ogy', 'dr.smith@rit.ac.in', 'Dr. Smith', 'FACULTY', 'CSE', '9000000001', true, NOW()),
('faculty2', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LPVyaKT0ogy', 'prof.john@rit.ac.in', 'Prof. John', 'FACULTY', 'CSE', '9000000002', true, NOW()),
('faculty3', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LPVyaKT0ogy', 'dr.alice@rit.ac.in', 'Dr. Alice', 'FACULTY', 'CSE', '9000000003', true, NOW());

-- Insert Students (5 users)
INSERT INTO users (username, password, email, full_name, role, department, phone_number, active, created_at)
VALUES 
('student1', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LPVyaKT0ogy', 'student1@rit.ac.in', 'Student One', 'STUDENT', 'CSE', '9000000004', true, NOW()),
('student2', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LPVyaKT0ogy', 'student2@rit.ac.in', 'Student Two', 'STUDENT', 'CSE', '9000000005', true, NOW()),
('student3', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LPVyaKT0ogy', 'student3@rit.ac.in', 'Student Three', 'STUDENT', 'CSE', '9000000006', true, NOW()),
('student4', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LPVyaKT0ogy', 'student4@rit.ac.in', 'Student Four', 'STUDENT', 'CSE', '9000000007', true, NOW()),
('student5', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LPVyaKT0ogy', 'student5@rit.ac.in', 'Student Five', 'STUDENT', 'CSE', '9000000008', true, NOW());

-- Map Faculty records
INSERT INTO faculty (user_id, employee_id, designation, department, subjects_handled, profile_complete)
VALUES 
((SELECT id FROM users WHERE username = 'faculty1'), 'F101', 'Professor', 'CSE', 'Data Structures', true),
((SELECT id FROM users WHERE username = 'faculty2'), 'F102', 'Assistant Professor', 'CSE', 'Mathematics III, OS Concepts', true),
((SELECT id FROM users WHERE username = 'faculty3'), 'F103', 'Associate Professor', 'CSE', 'Database Systems', true);

-- Map Student records
INSERT INTO students (user_id, roll_number, section, year, batch, department)
VALUES 
((SELECT id FROM users WHERE username = 'student1'), '21CS001', 'CSE-A', 2, '2021-2025', 'CSE'),
((SELECT id FROM users WHERE username = 'student2'), '21CS002', 'CSE-A', 2, '2021-2025', 'CSE'),
((SELECT id FROM users WHERE username = 'student3'), '21CS003', 'CSE-A', 2, '2021-2025', 'CSE'),
((SELECT id FROM users WHERE username = 'student4'), '21CS004', 'CSE-A', 2, '2021-2025', 'CSE'),
((SELECT id FROM users WHERE username = 'student5'), '21CS005', 'CSE-A', 2, '2021-2025', 'CSE');

-- Insert Subjects
INSERT INTO subjects (subject_code, subject_name, department, year, section, semester, faculty_id)
VALUES 
('CS201', 'Data Structures', 'CSE', 2, 'CSE-A', 3, (SELECT id FROM faculty WHERE employee_id = 'F101')),
('CS202', 'Mathematics III', 'CSE', 2, 'CSE-A', 3, (SELECT id FROM faculty WHERE employee_id = 'F102')),
('CS203', 'OS Concepts', 'CSE', 2, 'CSE-A', 3, (SELECT id FROM faculty WHERE employee_id = 'F102')),
('CS204', 'Database Systems', 'CSE', 2, 'CSE-A', 3, (SELECT id FROM faculty WHERE employee_id = 'F103'));

-- Insert Timetable (Example for Monday and Tuesday)
INSERT INTO timetable (day_of_week, period_number, start_time, end_time, department, year, section, subject_id, faculty_id, room_number)
VALUES 
('Monday', 1, '09:00:00', '09:50:00', 'CSE', 2, 'CSE-A', (SELECT id FROM subjects WHERE subject_code = 'CS201'), (SELECT id FROM faculty WHERE employee_id = 'F101'), 'Room 101'),
('Monday', 2, '09:50:00', '10:40:00', 'CSE', 2, 'CSE-A', (SELECT id FROM subjects WHERE subject_code = 'CS202'), (SELECT id FROM faculty WHERE employee_id = 'F102'), 'Room 101'),
('Monday', 3, '11:00:00', '11:50:00', 'CSE', 2, 'CSE-A', (SELECT id FROM subjects WHERE subject_code = 'CS203'), (SELECT id FROM faculty WHERE employee_id = 'F102'), 'Room 101'),
('Monday', 4, '11:50:00', '12:40:00', 'CSE', 2, 'CSE-A', (SELECT id FROM subjects WHERE subject_code = 'CS204'), (SELECT id FROM faculty WHERE employee_id = 'F103'), 'Room 101'),

('Tuesday', 1, '09:00:00', '09:50:00', 'CSE', 2, 'CSE-A', (SELECT id FROM subjects WHERE subject_code = 'CS204'), (SELECT id FROM faculty WHERE employee_id = 'F103'), 'Room 101'),
('Tuesday', 2, '09:50:00', '10:40:00', 'CSE', 2, 'CSE-A', (SELECT id FROM subjects WHERE subject_code = 'CS203'), (SELECT id FROM faculty WHERE employee_id = 'F102'), 'Room 101'),
('Tuesday', 3, '11:00:00', '11:50:00', 'CSE', 2, 'CSE-A', (SELECT id FROM subjects WHERE subject_code = 'CS202'), (SELECT id FROM faculty WHERE employee_id = 'F102'), 'Room 101'),
('Tuesday', 4, '11:50:00', '12:40:00', 'CSE', 2, 'CSE-A', (SELECT id FROM subjects WHERE subject_code = 'CS201'), (SELECT id FROM faculty WHERE employee_id = 'F101'), 'Room 101');
